### ISSUE TITLE
Action 排除 README

### ISSUE THREAD

**Issue by NeKoOuO** [xiaoyvyv/bangumi#64]
不然改一次就推送更新一次

**Comment by xihale** [comment]
参考：
```
on:
  push:
    paths-ignore:
      - README.md
```
